package com.project.back_end.services;

import com.project.back_end.repo.AdminRepository;
import com.project.back_end.repo.DoctorRepository;
import com.project.back_end.repo.PatientRepository;
import com.project.back_end.models.Admin;
import com.project.back_end.models.Doctor;
import com.project.back_end.models.Patient;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component; // @Component per spec

import javax.crypto.SecretKey;
import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * TokenService handles JWT generation, extraction, and validation.
 */
@Component
public class TokenService {
// 1. **@Component Annotation**
// The @Component annotation marks this class as a Spring component, meaning Spring will manage it as a bean within its application context.
// This allows the class to be injected into other Spring-managed components (like services or controllers) where it's needed.

    private final AdminRepository adminRepository;
    private final DoctorRepository doctorRepository;
    private final PatientRepository patientRepository;
    private final SecretKey signingKey;

    // Seven days in milliseconds
    private static final long EXPIRATION_MS = 7L * 24 * 60 * 60 * 1000;

    // 2. **Constructor Injection for Dependencies**
// The constructor injects dependencies for `AdminRepository`, `DoctorRepository`, and `PatientRepository`,
// allowing the service to interact with the database and validate users based on their role (admin, doctor, or patient).
// Constructor injection ensures that the class is initialized with all required dependencies, promoting immutability and making the class testable.
    public TokenService(AdminRepository adminRepository,
                        DoctorRepository doctorRepository,
                        PatientRepository patientRepository,
                        @Value("${jwt.secret}") String jwtSecret) {
        this.adminRepository = adminRepository;
        this.doctorRepository = doctorRepository;
        this.patientRepository = patientRepository;
        this.signingKey = buildKey(jwtSecret);
    }

    // 3. **getSigningKey Method**
// This method retrieves the HMAC SHA key used to sign JWT tokens.
// It uses the `jwt.secret` value, which is provided from an external source (like application properties).
// The `Keys.hmacShaKeyFor()` method converts the secret key string into a valid `SecretKey` for signing and verification of JWTs.
    public SecretKey getSigningKey() {
        return signingKey;
    }

    private SecretKey buildKey(String secret) {
        // Accept both plain text (>= 32 chars recommended) or Base64-encoded secrets
        byte[] keyBytes = secret.matches("^[A-Za-z0-9+/=]+$") && secret.length() % 4 == 0
                ? Decoders.BASE64.decode(secret)
                : secret.getBytes();
        return Keys.hmacShaKeyFor(keyBytes);
    }

    // 4. **generateToken Method**
// This method generates a JWT token for a user based on their email.
// - The `subject` of the token is set to the user's email, which is used as an identifier.
// - The `issuedAt` is set to the current date and time.
// - The `expiration` is set to 7 days from the issue date, ensuring the token expires after one week.
// - The token is signed using the signing key generated by `getSigningKey()`, making it secure and tamper-proof.
// The method returns the JWT token as a string.
    public String generateToken(String identifier) {
        Date now = new Date();
        Date exp = new Date(now.getTime() + EXPIRATION_MS);
        return Jwts.builder()
                .setSubject(identifier)
                .setIssuedAt(now)
                .setExpiration(exp)
                .signWith(getSigningKey(), SignatureAlgorithm.HS256)
                .compact();
    }

    // Convenience overload used by other services (adds a "role" claim).
// Fixed: replaced .setClaims(Map) with .claim("role", role) to preserve subject and other claims.
    public String generateToken(String identifier, String role) {
        Date now = new Date();
        Date exp = new Date(now.getTime() + EXPIRATION_MS);
        return Jwts.builder()
                .setSubject(identifier)
                .claim("role", role)
                .setIssuedAt(now)
                .setExpiration(exp)
                .signWith(getSigningKey(), SignatureAlgorithm.HS256)
                .compact();
    }

    // 5. **extractEmail Method**
// This method extracts the user's email (subject) from the provided JWT token.
// - The token is first verified using the signing key to ensure it hasn’t been tampered with.
// - After verification, the token is parsed, and the subject (which represents the email) is extracted.
// This method allows the application to retrieve the user's identity (email) from the token for further use.
    public String extractEmail(String token) {
        return extractIdentifier(token);
    }

    // Alias used elsewhere
    public String extractSubject(String token) {
        return extractIdentifier(token);
    }

    // Spec method name:
// Fixed parser usage for JJWT 0.12.x — if you’re using 0.11.x, uncomment the alternate lines below.
    public String extractIdentifier(String token) {
        Claims claims = Jwts.parser()
                .verifyWith(getSigningKey()) // 0.12.x parser syntax
                .build()
                .parseSignedClaims(clean(token))
                .getPayload();

        // For JJWT 0.11.x:
        // Claims claims = Jwts.parserBuilder()
        //        .setSigningKey(getSigningKey())
        //        .build()
        //        .parseClaimsJws(clean(token))
        //        .getBody();

        return claims.getSubject();
    }

    // 6. **validateToken Method**
// This method validates whether a provided JWT token is valid for a specific user role (admin, doctor, or patient).
// - It first extracts the email from the token using the `extractEmail()` method.
// - Depending on the role (`admin`, `doctor`, or `patient`), it checks the corresponding repository (AdminRepository, DoctorRepository, or PatientRepository)
//   to see if a user with the extracted email exists.
// - If a match is found for the specified user role, it returns true, indicating the token is valid.
// - If the role or user does not exist, it returns false, indicating the token is invalid.
// - The method gracefully handles any errors by returning false if the token is invalid or an exception occurs.
// This ensures secure access control based on the user's role and their existence in the system.
    public boolean validateToken(String token, String user) {
        try {
            Claims claims = Jwts.parser()
                    .verifyWith(getSigningKey()) // 0.12.x
                    .build()
                    .parseSignedClaims(clean(token))
                    .getPayload();

            // Check expiration
            Date exp = claims.getExpiration();
            if (exp == null || exp.before(new Date())) return false;

            String identifier = claims.getSubject();
            if (identifier == null || identifier.isBlank()) return false;

            String userType = user == null ? "" : user.trim().toLowerCase(Locale.ROOT);
            switch (userType) {
                case "admin": {
                    // For admins, identifier = username
                    Admin admin = adminRepository.findByUsername(identifier);
                    return admin != null;
                }
                case "doctor": {
                    // For doctors, identifier = email
                    Doctor doctor = doctorRepository.findByEmail(identifier);
                    return doctor != null;
                }
                case "patient": {
                    // For patients, identifier = email
                    Patient patient = patientRepository.findByEmail(identifier);
                    return patient != null;
                }
                default:
                    // Unknown user type — treat as invalid for role-bound validation
                    return false;
            }
        } catch (Exception e) {
            return false;
        }
    }

    // Lightweight boolean validation used by other services (signature & expiration only).
    public boolean validateToken(String token) {
        try {
            Claims claims = Jwts.parser()
                    .verifyWith(getSigningKey()) // 0.12.x syntax
                    .build()
                    .parseSignedClaims(clean(token))
                    .getPayload();
            Date exp = claims.getExpiration();
            return exp != null && exp.after(new Date()) && claims.getSubject() != null;
        } catch (Exception e) {
            return false;
        }
    }

    private String clean(String token) {
        if (token == null) return "";
        String t = token.trim();
        if (t.toLowerCase(Locale.ROOT).startsWith("bearer ")) {
            return t.substring(7).trim();
        }
        return t;
    }

    // 7. **generateTokenForDoctor Method**
// This method generates a JWT token specifically for a doctor user.
// - Includes custom claims like "uid" for the doctor ID and "role" for their access level.
// - The subject (sub) is set to the doctor's email, which serves as their unique identifier.
    public String generateTokenForDoctor(Doctor doctor) {
        if (doctor == null) throw new IllegalArgumentException("doctor cannot be null");
        Date now = new Date();
        Date exp = new Date(now.getTime() + EXPIRATION_MS);
        return Jwts.builder()
                .setSubject(doctor.getEmail())
                .claim("uid", doctor.getId())
                .claim("role", "DOCTOR")
                .setIssuedAt(now)
                .setExpiration(exp)
                .signWith(getSigningKey(), SignatureAlgorithm.HS256)
                .compact();
    }

    // 8. **extractUserId Method**
// This method extracts the "uid" claim from the token.
// - It represents the unique user ID of the token owner (doctor, patient, etc.).
// - Returns null if the claim doesn’t exist or parsing fails.
    public Long extractUserId(String token) {
        try {
            Claims claims = Jwts.parser()
                    .verifyWith(getSigningKey())
                    .build()
                    .parseSignedClaims(clean(token))
                    .getPayload();
            Object v = claims.get("uid");
            if (v instanceof Number n) return n.longValue();
            if (v instanceof String s) return Long.parseLong(s);
            return null;
        } catch (Exception e) {
            return null;
        }
    }

    // 9. **extractRole Method**
// This method retrieves the "role" claim from the token.
// - Returns a string indicating the user’s role (e.g., "DOCTOR", "PATIENT", "ADMIN").
// - Returns null if the claim is not present.
    public String extractRole(String token) {
        try {
            Claims claims = Jwts.parser()
                    .verifyWith(getSigningKey())
                    .build()
                    .parseSignedClaims(clean(token))
                    .getPayload();
            Object v = claims.get("role");
            return v == null ? null : String.valueOf(v);
        } catch (Exception e) {
            return null;
        }
    }
}
